//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vilka
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetOffer
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public int BetTypeID { get; set; }
        public Nullable<int> BetTargetID { get; set; }
    
        public virtual BetTarget BetTarget { get; set; }
        public virtual BetType BetType { get; set; }
        public virtual Event Event { get; set; }
    }
}
